<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.BarCode" Version="26.4.0" />
    <PackageReference Include="Aspose.PDF.Drawing" Version="23.9.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260427" />
    <PackageReference Include="PuppeteerSharp" Version="24.39.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.116.1" />
    <PackageReference Include="SMBLibrary" Version="1.5.5" />
    <PackageReference Include="SSH.NET" Version="2025.1.0" />
    <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" Version="0.16.21" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DevExpress.Data.v20.2">
      <HintPath>DLL\DevExpress.Data.v20.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Docs.v20.2">
      <HintPath>DLL\DevExpress.Docs.v20.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Pdf.v20.2.Core">
      <HintPath>DLL\DevExpress.Pdf.v20.2.Core.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Pdf.v20.2.Drawing">
      <HintPath>DLL\DevExpress.Pdf.v20.2.Drawing.dll</HintPath>
    </Reference>
    <Reference Include="OpenCvSharpExtern">
      <HintPath>DLL\OpenCvSharpExtern.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
